### ISSUE TITLE
Sound Engine Questions

### ISSUE THREAD

**Issue by Kfeavel** [lufinkey/MobileBrawler#10]
As mentioned in one of the earlier pull request discussions, a new sound engine will be necessary since we won't be using the old one. Here are the following questions I have about the new sound engine:
1) Are you simply wanting it more flexible, making a "port" of the old system an ideal starting point?
2) Are you completely wanting to rewrite it from scratch and if so, question 3 applies.
3) What are you wanting the new system to do that the older one was incapable of or ineffecient?

**Comment by lufinkey** [comment]
SDL_mixer only lets you play a single music track at a time, which is fine for simple things, but I'd rather have the flexibility there to play multiple tracks. Multiple sounds can still be played at the same time in SDL_mixer, so if we really need to use it, we still can. (also we should use g+ hangouts to discuss these kinds of things, since they're not really issues)

**Comment by Kfeavel** [comment]
I wanted to put it here as more of a checklist but I can take it down if you'd like.

**Comment by lufinkey** [comment]
that's true. I'll just leave it
